version: '2'

services:
    meinheld-vcard:
        build: .
        image: meinheld-django
        container_name: meinheld-vcard
        network_mode: host
        labels:
            version: '1.0'
        environment:
            APP_NAME: front
        volumes:
            - /data/code/vcard/front:/home/docker/code/app
